import 'dotenv/config';
import { v4 as uuidv4 } from 'uuid';
import db from './database';
import { initSchema } from './schema';

initSchema();

const existing = db.prepare('SELECT COUNT(*) as count FROM products').get() as { count: number };
if (existing.count > 0) {
  console.log(`Database already has ${existing.count} products. Skipping seed.`);
  process.exit(0);
}

interface SeedProduct {
  title: string;
  description: string;
  sku: string;
  brand: string;
  category: string;
  subcategory: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  stockCount: number;
  imageUrl: string;
  attributes: Record<string, string>;
  tags: string[];
}

const products: SeedProduct[] = [
  // Electronics - Smartphones
  {
    title: 'Apple iPhone 16 Pro 256GB',
    description: 'The latest iPhone with A18 Pro chip, titanium design, and advanced camera system with 5x optical zoom.',
    sku: 'APPL-IP16P-256',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Smartphones',
    price: 1099.99,
    rating: 4.8,
    reviewCount: 3421,
    inStock: true,
    stockCount: 45,
    imageUrl: 'https://placehold.co/400x400?text=iPhone+16+Pro',
    attributes: { color: 'Natural Titanium', storage: '256GB', network: '5G' },
    tags: ['new', 'flagship', 'apple'],
  },
  {
    title: 'Samsung Galaxy S25 Ultra 512GB',
    description: 'Samsung flagship with Snapdragon 8 Elite, built-in S Pen, and 200MP main camera.',
    sku: 'SAMS-S25U-512',
    brand: 'Samsung',
    category: 'Electronics',
    subcategory: 'Smartphones',
    price: 1299.99,
    originalPrice: 1399.99,
    rating: 4.7,
    reviewCount: 2187,
    inStock: true,
    stockCount: 28,
    imageUrl: 'https://placehold.co/400x400?text=Galaxy+S25+Ultra',
    attributes: { color: 'Titanium Black', storage: '512GB', network: '5G' },
    tags: ['new', 'flagship', 'samsung', 'sale'],
  },
  {
    title: 'Google Pixel 9 128GB',
    description: 'Pure Android experience with Google Tensor G4 chip and exceptional computational photography.',
    sku: 'GOOG-PX9-128',
    brand: 'Google',
    category: 'Electronics',
    subcategory: 'Smartphones',
    price: 799.99,
    rating: 4.6,
    reviewCount: 891,
    inStock: true,
    stockCount: 60,
    imageUrl: 'https://placehold.co/400x400?text=Pixel+9',
    attributes: { color: 'Obsidian', storage: '128GB', network: '5G' },
    tags: ['android', 'google'],
  },
  // Electronics - Laptops
  {
    title: 'Apple MacBook Pro 14" M4',
    description: 'Professional laptop with M4 chip, 16GB unified memory, and Liquid Retina XDR display.',
    sku: 'APPL-MBP14-M4',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Laptops',
    price: 1999.99,
    rating: 4.9,
    reviewCount: 1542,
    inStock: true,
    stockCount: 20,
    imageUrl: 'https://placehold.co/400x400?text=MacBook+Pro+14',
    attributes: { color: 'Space Black', ram: '16GB', storage: '512GB SSD' },
    tags: ['new', 'professional', 'apple'],
  },
  {
    title: 'Dell XPS 15 9530',
    description: 'Premium Windows laptop with Intel Core i7-13700H, OLED display, and NVIDIA RTX 4060.',
    sku: 'DELL-XPS15-9530',
    brand: 'Dell',
    category: 'Electronics',
    subcategory: 'Laptops',
    price: 1649.99,
    originalPrice: 1849.99,
    rating: 4.5,
    reviewCount: 673,
    inStock: true,
    stockCount: 15,
    imageUrl: 'https://placehold.co/400x400?text=Dell+XPS+15',
    attributes: { color: 'Platinum Silver', ram: '16GB', storage: '512GB SSD' },
    tags: ['sale', 'windows', 'gaming'],
  },
  {
    title: 'Lenovo ThinkPad X1 Carbon Gen 12',
    description: 'Business ultrabook with Intel Core Ultra 7, 32GB RAM, and legendary keyboard.',
    sku: 'LENO-X1C-G12',
    brand: 'Lenovo',
    category: 'Electronics',
    subcategory: 'Laptops',
    price: 1549.99,
    rating: 4.7,
    reviewCount: 428,
    inStock: false,
    stockCount: 0,
    imageUrl: 'https://placehold.co/400x400?text=ThinkPad+X1',
    attributes: { color: 'Black', ram: '32GB', storage: '1TB SSD' },
    tags: ['business', 'ultrabook'],
  },
  // Electronics - Headphones
  {
    title: 'Sony WH-1000XM5',
    description: 'Industry-leading noise canceling headphones with 30-hour battery and multipoint connection.',
    sku: 'SONY-WH1000XM5',
    brand: 'Sony',
    category: 'Electronics',
    subcategory: 'Headphones',
    price: 349.99,
    originalPrice: 399.99,
    rating: 4.8,
    reviewCount: 8921,
    inStock: true,
    stockCount: 120,
    imageUrl: 'https://placehold.co/400x400?text=Sony+WH-1000XM5',
    attributes: { color: 'Black', type: 'Over-ear', connectivity: 'Bluetooth' },
    tags: ['bestseller', 'noise-canceling', 'sale'],
  },
  {
    title: 'Apple AirPods Pro 2nd Gen',
    description: 'Active Noise Cancellation, Adaptive Transparency, and Personalized Spatial Audio.',
    sku: 'APPL-APP2-USB',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Headphones',
    price: 249.99,
    rating: 4.7,
    reviewCount: 12453,
    inStock: true,
    stockCount: 200,
    imageUrl: 'https://placehold.co/400x400?text=AirPods+Pro+2',
    attributes: { color: 'White', type: 'In-ear', connectivity: 'Bluetooth' },
    tags: ['bestseller', 'apple', 'wireless'],
  },
  // Clothing - Men
  {
    title: "Levi's 501 Original Fit Jeans",
    description: "The original straight fit jeans that started it all. Made from 100% cotton denim.",
    sku: 'LEVI-501-32x32',
    brand: "Levi's",
    category: 'Clothing',
    subcategory: "Men's Jeans",
    price: 69.99,
    rating: 4.5,
    reviewCount: 15672,
    inStock: true,
    stockCount: 300,
    imageUrl: 'https://placehold.co/400x400?text=Levis+501',
    attributes: { color: 'Stonewash Blue', size: '32x32', material: 'Cotton' },
    tags: ['classic', 'casual'],
  },
  {
    title: 'Ralph Lauren Oxford Shirt',
    description: 'Classic button-down oxford shirt in 100% cotton. Machine washable.',
    sku: 'RL-OXF-WHT-L',
    brand: 'Ralph Lauren',
    category: 'Clothing',
    subcategory: "Men's Shirts",
    price: 98.99,
    originalPrice: 125.00,
    rating: 4.6,
    reviewCount: 2341,
    inStock: true,
    stockCount: 85,
    imageUrl: 'https://placehold.co/400x400?text=RL+Oxford',
    attributes: { color: 'White', size: 'L', material: 'Cotton' },
    tags: ['classic', 'formal', 'sale'],
  },
  {
    title: 'Nike Tech Fleece Hoodie',
    description: 'Engineered to keep you warm without the bulk. Soft, breathable fleece construction.',
    sku: 'NIKE-TF-HOOD-BLK-M',
    brand: 'Nike',
    category: 'Clothing',
    subcategory: "Men's Hoodies",
    price: 110.00,
    rating: 4.4,
    reviewCount: 4532,
    inStock: true,
    stockCount: 150,
    imageUrl: 'https://placehold.co/400x400?text=Nike+Tech+Fleece',
    attributes: { color: 'Black', size: 'M', material: 'Polyester' },
    tags: ['sport', 'casual'],
  },
  // Clothing - Women
  {
    title: 'Zara Wide Leg Trousers',
    description: 'High-waisted wide leg trousers in premium fabric. Perfect for office and evening wear.',
    sku: 'ZARA-WLT-BLK-S',
    brand: 'Zara',
    category: 'Clothing',
    subcategory: "Women's Trousers",
    price: 49.99,
    rating: 4.3,
    reviewCount: 789,
    inStock: true,
    stockCount: 60,
    imageUrl: 'https://placehold.co/400x400?text=Zara+Trousers',
    attributes: { color: 'Black', size: 'S', material: 'Polyester blend' },
    tags: ['trending', 'office'],
  },
  {
    title: "H&M Linen Blend Blazer",
    description: 'Structured blazer in linen blend. Single-button fastening with notch lapels.',
    sku: 'HM-LBZ-BEI-M',
    brand: 'H&M',
    category: 'Clothing',
    subcategory: "Women's Blazers",
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.2,
    reviewCount: 456,
    inStock: true,
    stockCount: 40,
    imageUrl: 'https://placehold.co/400x400?text=HM+Blazer',
    attributes: { color: 'Beige', size: 'M', material: 'Linen blend' },
    tags: ['office', 'sale'],
  },
  // Footwear
  {
    title: 'Nike Air Max 270',
    description: "Nike's first lifestyle Air Max shoe with a 270-degree visible heel Air unit.",
    sku: 'NIKE-AM270-WHT-10',
    brand: 'Nike',
    category: 'Footwear',
    subcategory: 'Sneakers',
    price: 150.00,
    rating: 4.5,
    reviewCount: 6789,
    inStock: true,
    stockCount: 90,
    imageUrl: 'https://placehold.co/400x400?text=Air+Max+270',
    attributes: { color: 'White/Black', size: '10', material: 'Mesh/Synthetic' },
    tags: ['running', 'lifestyle'],
  },
  {
    title: 'Adidas Stan Smith',
    description: 'Iconic tennis-inspired sneaker with perforated 3-Stripes and clean leather upper.',
    sku: 'ADID-SS-WHT-GRN-9',
    brand: 'Adidas',
    category: 'Footwear',
    subcategory: 'Sneakers',
    price: 90.00,
    rating: 4.6,
    reviewCount: 11234,
    inStock: true,
    stockCount: 200,
    imageUrl: 'https://placehold.co/400x400?text=Stan+Smith',
    attributes: { color: 'White/Green', size: '9', material: 'Leather' },
    tags: ['classic', 'casual', 'bestseller'],
  },
  {
    title: 'Timberland 6-Inch Premium Boot',
    description: 'Waterproof nubuck leather upper with seam-sealed construction. The original yellow boot.',
    sku: 'TIMB-6IN-WHT-11',
    brand: 'Timberland',
    category: 'Footwear',
    subcategory: 'Boots',
    price: 200.00,
    originalPrice: 230.00,
    rating: 4.7,
    reviewCount: 8901,
    inStock: true,
    stockCount: 55,
    imageUrl: 'https://placehold.co/400x400?text=Timberland+Boot',
    attributes: { color: 'Wheat', size: '11', material: 'Nubuck leather' },
    tags: ['waterproof', 'outdoor', 'sale'],
  },
  {
    title: 'Birkenstock Arizona Sandals',
    description: 'Classic two-strap sandal with contoured cork-latex footbed for exceptional support.',
    sku: 'BIRK-ARI-BRN-42',
    brand: 'Birkenstock',
    category: 'Footwear',
    subcategory: 'Sandals',
    price: 110.00,
    rating: 4.8,
    reviewCount: 7654,
    inStock: false,
    stockCount: 0,
    imageUrl: 'https://placehold.co/400x400?text=Birkenstock+Arizona',
    attributes: { color: 'Brown', size: '42', material: 'Suede' },
    tags: ['comfort', 'summer'],
  },
  // Home & Garden
  {
    title: 'Dyson V15 Detect Cordless Vacuum',
    description: 'Reveals invisible dust with a laser. Auto-adjusts suction power based on dust levels.',
    sku: 'DYSO-V15-DET',
    brand: 'Dyson',
    category: 'Home & Garden',
    subcategory: 'Vacuum Cleaners',
    price: 699.99,
    originalPrice: 749.99,
    rating: 4.8,
    reviewCount: 3241,
    inStock: true,
    stockCount: 30,
    imageUrl: 'https://placehold.co/400x400?text=Dyson+V15',
    attributes: { color: 'Yellow/Nickel', type: 'Cordless', runtime: '60 min' },
    tags: ['bestseller', 'cordless', 'sale'],
  },
  {
    title: 'Nespresso Vertuo Next Coffee Machine',
    description: 'Brew 5 cup sizes from espresso to Alto XL. Bluetooth connected with one-touch brewing.',
    sku: 'NESP-VTNXT-BLK',
    brand: 'Nespresso',
    category: 'Home & Garden',
    subcategory: 'Coffee Machines',
    price: 179.99,
    rating: 4.6,
    reviewCount: 5678,
    inStock: true,
    stockCount: 70,
    imageUrl: 'https://placehold.co/400x400?text=Nespresso+Vertuo',
    attributes: { color: 'Black', type: 'Pod machine', capacity: '1.1L' },
    tags: ['kitchen', 'coffee'],
  },
  {
    title: 'Philips Hue Starter Kit (3 bulbs + Bridge)',
    description: 'Smart lighting starter kit. Control 16 million colors and warm-to-cool white light.',
    sku: 'PHIL-HUE-SK3',
    brand: 'Philips',
    category: 'Home & Garden',
    subcategory: 'Smart Home',
    price: 149.99,
    rating: 4.5,
    reviewCount: 4321,
    inStock: true,
    stockCount: 45,
    imageUrl: 'https://placehold.co/400x400?text=Philips+Hue',
    attributes: { color: 'White', voltage: '220V', compatibility: 'Alexa/Google' },
    tags: ['smart-home', 'alexa', 'google-home'],
  },
  // Sports
  {
    title: 'Garmin Forerunner 265 GPS Watch',
    description: 'Running smartwatch with AMOLED display, HRV status, race predictor, and 15-day battery.',
    sku: 'GARM-FR265-BLK',
    brand: 'Garmin',
    category: 'Sports',
    subcategory: 'Smartwatches',
    price: 449.99,
    rating: 4.7,
    reviewCount: 1876,
    inStock: true,
    stockCount: 35,
    imageUrl: 'https://placehold.co/400x400?text=Garmin+FR265',
    attributes: { color: 'Black/Aqua', display: 'AMOLED', gps: 'Multi-band' },
    tags: ['running', 'fitness', 'gps'],
  },
  {
    title: 'Yeti Rambler 30oz Tumbler',
    description: 'Double-wall vacuum insulation keeps drinks cold or hot. Dishwasher safe.',
    sku: 'YETI-R30-CHAR',
    brand: 'Yeti',
    category: 'Sports',
    subcategory: 'Water Bottles',
    price: 38.99,
    rating: 4.8,
    reviewCount: 28901,
    inStock: true,
    stockCount: 500,
    imageUrl: 'https://placehold.co/400x400?text=Yeti+Rambler',
    attributes: { color: 'Charcoal', capacity: '30oz', material: 'Stainless steel' },
    tags: ['bestseller', 'outdoor'],
  },
  {
    title: 'Theragun Prime Massage Gun',
    description: 'Quiet, powerful percussive therapy device with 5 speeds and 4 attachments.',
    sku: 'THERA-PRIME-BLK',
    brand: 'Theragun',
    category: 'Sports',
    subcategory: 'Recovery',
    price: 299.99,
    originalPrice: 349.99,
    rating: 4.6,
    reviewCount: 3456,
    inStock: true,
    stockCount: 40,
    imageUrl: 'https://placehold.co/400x400?text=Theragun+Prime',
    attributes: { color: 'Black', speeds: '5', battery: '120 min' },
    tags: ['recovery', 'fitness', 'sale'],
  },
  // More Electronics
  {
    title: 'iPad Air 11" M2',
    description: 'Thin, light, and powerful with M2 chip, 11-inch Liquid Retina display, and Apple Pencil Pro support.',
    sku: 'APPL-IPAD-AIR11-M2',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Tablets',
    price: 599.99,
    rating: 4.8,
    reviewCount: 2341,
    inStock: true,
    stockCount: 55,
    imageUrl: 'https://placehold.co/400x400?text=iPad+Air+M2',
    attributes: { color: 'Blue', storage: '128GB', connectivity: 'WiFi' },
    tags: ['apple', 'new'],
  },
  {
    title: 'LG C4 OLED 55" 4K TV',
    description: 'Self-lit OLED pixels for perfect black and infinite contrast. Powered by α9 AI Processor Gen7.',
    sku: 'LG-C4-OLED55',
    brand: 'LG',
    category: 'Electronics',
    subcategory: 'TVs',
    price: 1296.99,
    originalPrice: 1499.99,
    rating: 4.9,
    reviewCount: 4521,
    inStock: true,
    stockCount: 12,
    imageUrl: 'https://placehold.co/400x400?text=LG+C4+OLED',
    attributes: { size: '55"', resolution: '4K', panelType: 'OLED' },
    tags: ['sale', 'bestseller', '4k'],
  },
  // More Clothing
  {
    title: 'Patagonia Nano Puff Jacket',
    description: 'Ultralight, compressible, wind and water resistant insulation for cool weather adventures.',
    sku: 'PATA-NPJ-BLK-L',
    brand: 'Patagonia',
    category: 'Clothing',
    subcategory: "Men's Jackets",
    price: 229.00,
    rating: 4.7,
    reviewCount: 3456,
    inStock: true,
    stockCount: 28,
    imageUrl: 'https://placehold.co/400x400?text=Nano+Puff',
    attributes: { color: 'Black', size: 'L', material: 'Recycled polyester' },
    tags: ['outdoor', 'sustainable'],
  },
  {
    title: "Arc'teryx Beta Jacket",
    description: 'The standard in Gore-Tex waterproof breathable shell jackets for alpine climbing.',
    sku: 'ARCT-BETA-NVY-M',
    brand: "Arc'teryx",
    category: 'Clothing',
    subcategory: "Men's Jackets",
    price: 700.00,
    rating: 4.9,
    reviewCount: 1234,
    inStock: false,
    stockCount: 0,
    imageUrl: 'https://placehold.co/400x400?text=Beta+Jacket',
    attributes: { color: 'Navy', size: 'M', material: 'Gore-Tex' },
    tags: ['premium', 'waterproof', 'alpine'],
  },
  {
    title: 'Uniqlo Ultra Light Down Jacket',
    description: 'Incredibly lightweight and warm down jacket that folds into its own pocket.',
    sku: 'UNIQ-ULD-BLK-S',
    brand: 'Uniqlo',
    category: 'Clothing',
    subcategory: "Men's Jackets",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviewCount: 7890,
    inStock: true,
    stockCount: 100,
    imageUrl: 'https://placehold.co/400x400?text=Uniqlo+Down',
    attributes: { color: 'Black', size: 'S', material: '90% down' },
    tags: ['lightweight', 'packable', 'sale'],
  },
  // More Footwear
  {
    title: 'New Balance 990v6',
    description: 'Made in USA. Premium pigskin and mesh upper with ENCAP midsole cushioning.',
    sku: 'NB-990V6-GRY-11',
    brand: 'New Balance',
    category: 'Footwear',
    subcategory: 'Sneakers',
    price: 184.99,
    rating: 4.8,
    reviewCount: 5432,
    inStock: true,
    stockCount: 45,
    imageUrl: 'https://placehold.co/400x400?text=NB+990v6',
    attributes: { color: 'Grey', size: '11', material: 'Pigskin/Mesh' },
    tags: ['made-in-usa', 'running', 'classic'],
  },
  {
    title: 'Converse Chuck Taylor All Star',
    description: 'The original basketball shoe turned cultural icon. Canvas upper with rubber sole.',
    sku: 'CONV-CTAS-BLK-9',
    brand: 'Converse',
    category: 'Footwear',
    subcategory: 'Sneakers',
    price: 65.00,
    rating: 4.5,
    reviewCount: 45678,
    inStock: true,
    stockCount: 400,
    imageUrl: 'https://placehold.co/400x400?text=Chuck+Taylor',
    attributes: { color: 'Black', size: '9', material: 'Canvas' },
    tags: ['classic', 'casual', 'icon'],
  },
  // More Home & Garden
  {
    title: 'KitchenAid Stand Mixer 5Qt',
    description: 'Tilt-head design with 10 speeds and included flat beater, dough hook, and wire whip.',
    sku: 'KAID-KSM150-RED',
    brand: 'KitchenAid',
    category: 'Home & Garden',
    subcategory: 'Kitchen Appliances',
    price: 449.99,
    originalPrice: 499.99,
    rating: 4.9,
    reviewCount: 12345,
    inStock: true,
    stockCount: 25,
    imageUrl: 'https://placehold.co/400x400?text=KitchenAid+Mixer',
    attributes: { color: 'Empire Red', capacity: '5Qt', power: '325W' },
    tags: ['baking', 'bestseller', 'sale'],
  },
  {
    title: 'Instant Pot Duo 7-in-1 6Qt',
    description: 'Pressure cooker, slow cooker, rice cooker, steamer, saute, yogurt maker, and warmer.',
    sku: 'INST-DUO60-BLK',
    brand: 'Instant Pot',
    category: 'Home & Garden',
    subcategory: 'Kitchen Appliances',
    price: 89.99,
    originalPrice: 109.99,
    rating: 4.7,
    reviewCount: 67890,
    inStock: true,
    stockCount: 150,
    imageUrl: 'https://placehold.co/400x400?text=Instant+Pot',
    attributes: { color: 'Black', capacity: '6Qt', functions: '7-in-1' },
    tags: ['kitchen', 'bestseller', 'sale'],
  },
  // More Sports
  {
    title: 'Hydro Flask 32oz Wide Mouth',
    description: 'TempShield insulation keeps drinks cold 24 hours and hot 12 hours. BPA-free.',
    sku: 'HYDR-32WM-BLUE',
    brand: 'Hydro Flask',
    category: 'Sports',
    subcategory: 'Water Bottles',
    price: 49.95,
    rating: 4.8,
    reviewCount: 34567,
    inStock: true,
    stockCount: 300,
    imageUrl: 'https://placehold.co/400x400?text=Hydro+Flask',
    attributes: { color: 'Pacific', capacity: '32oz', material: 'Stainless steel' },
    tags: ['outdoor', 'hiking'],
  },
  {
    title: 'Manduka PRO Yoga Mat 6mm',
    description: 'Lifetime guarantee. Dense 6mm cushion, closed-cell surface prevents bacteria absorption.',
    sku: 'MAND-PRO-BLK-6MM',
    brand: 'Manduka',
    category: 'Sports',
    subcategory: 'Yoga',
    price: 120.00,
    rating: 4.8,
    reviewCount: 5678,
    inStock: true,
    stockCount: 80,
    imageUrl: 'https://placehold.co/400x400?text=Manduka+PRO',
    attributes: { color: 'Black', thickness: '6mm', material: 'PVC' },
    tags: ['yoga', 'premium'],
  },
  // Additional products
  {
    title: 'Samsung 49" Odyssey G9 Gaming Monitor',
    description: 'DQHD resolution, 1ms response time, 240Hz refresh rate curved gaming monitor.',
    sku: 'SAMS-G9-49',
    brand: 'Samsung',
    category: 'Electronics',
    subcategory: 'Monitors',
    price: 999.99,
    originalPrice: 1199.99,
    rating: 4.6,
    reviewCount: 2341,
    inStock: true,
    stockCount: 8,
    imageUrl: 'https://placehold.co/400x400?text=Odyssey+G9',
    attributes: { size: '49"', resolution: 'DQHD', refreshRate: '240Hz' },
    tags: ['gaming', 'ultrawide', 'sale'],
  },
  {
    title: 'Logitech MX Master 3S Mouse',
    description: 'Advanced wireless mouse with 8K DPI sensor, MagSpeed scroll wheel, and ergonomic design.',
    sku: 'LOGI-MXM3S-BLK',
    brand: 'Logitech',
    category: 'Electronics',
    subcategory: 'Peripherals',
    price: 99.99,
    rating: 4.8,
    reviewCount: 7890,
    inStock: true,
    stockCount: 90,
    imageUrl: 'https://placehold.co/400x400?text=MX+Master+3S',
    attributes: { color: 'Graphite', connectivity: 'Bluetooth/USB', dpi: '8000' },
    tags: ['productivity', 'wireless'],
  },
  {
    title: "Levi's 512 Slim Taper Jeans",
    description: "Slim through the thigh and tapered to the ankle. Made from stretch denim for comfort.",
    sku: 'LEVI-512-30x30',
    brand: "Levi's",
    category: 'Clothing',
    subcategory: "Men's Jeans",
    price: 79.99,
    rating: 4.4,
    reviewCount: 5678,
    inStock: true,
    stockCount: 120,
    imageUrl: 'https://placehold.co/400x400?text=Levis+512',
    attributes: { color: 'Indigo', size: '30x30', material: 'Stretch denim' },
    tags: ['slim', 'casual'],
  },
  {
    title: 'Champion Reverse Weave Hoodie',
    description: 'The original reverse weave construction reduces shrinkage. 82% cotton, 18% polyester.',
    sku: 'CHAMP-RW-HOOD-GRY-L',
    brand: 'Champion',
    category: 'Clothing',
    subcategory: "Men's Hoodies",
    price: 55.00,
    rating: 4.5,
    reviewCount: 9012,
    inStock: true,
    stockCount: 200,
    imageUrl: 'https://placehold.co/400x400?text=Champion+Hoodie',
    attributes: { color: 'Oxford Grey', size: 'L', material: 'Cotton/Polyester' },
    tags: ['classic', 'casual', 'bestseller'],
  },
  {
    title: 'On Cloud 5 Running Shoes',
    description: 'Swiss engineered running shoes with CloudTec cushioning and zero-gravity feel.',
    sku: 'ON-CLD5-WHT-10',
    brand: 'On',
    category: 'Footwear',
    subcategory: 'Running Shoes',
    price: 139.99,
    rating: 4.6,
    reviewCount: 3456,
    inStock: true,
    stockCount: 65,
    imageUrl: 'https://placehold.co/400x400?text=On+Cloud+5',
    attributes: { color: 'White/Black', size: '10', material: 'Mesh' },
    tags: ['running', 'swiss'],
  },
  {
    title: 'HOKA Clifton 9',
    description: 'Maximum cushion running shoe with a balanced, soft ride and improved upper fit.',
    sku: 'HOKA-CLF9-BLK-10',
    brand: 'HOKA',
    category: 'Footwear',
    subcategory: 'Running Shoes',
    price: 145.00,
    rating: 4.7,
    reviewCount: 4567,
    inStock: true,
    stockCount: 50,
    imageUrl: 'https://placehold.co/400x400?text=HOKA+Clifton+9',
    attributes: { color: 'Black', size: '10', material: 'Mesh' },
    tags: ['running', 'max-cushion'],
  },
  {
    title: 'iRobot Roomba j7+',
    description: 'Self-emptying robot vacuum that avoids objects like pet waste and cords. P.O.O.P. guarantee.',
    sku: 'IROB-J7PLUS',
    brand: 'iRobot',
    category: 'Home & Garden',
    subcategory: 'Robot Vacuums',
    price: 499.99,
    originalPrice: 599.99,
    rating: 4.5,
    reviewCount: 6789,
    inStock: true,
    stockCount: 20,
    imageUrl: 'https://placehold.co/400x400?text=Roomba+j7+',
    attributes: { color: 'Graphite', suction: '10x', dustbin: 'Self-emptying' },
    tags: ['smart-home', 'sale'],
  },
  {
    title: 'Breville Barista Express',
    description: 'Grind-to-espresso machine with integrated conical burr grinder and steam wand.',
    sku: 'BREV-BES870BSS',
    brand: 'Breville',
    category: 'Home & Garden',
    subcategory: 'Coffee Machines',
    price: 699.99,
    rating: 4.7,
    reviewCount: 8901,
    inStock: true,
    stockCount: 18,
    imageUrl: 'https://placehold.co/400x400?text=Barista+Express',
    attributes: { color: 'Brushed Stainless', type: 'Espresso', grinder: 'Built-in' },
    tags: ['espresso', 'premium', 'barista'],
  },
  {
    title: 'Fitbit Charge 6',
    description: 'Advanced health and fitness tracker with Google Maps, YouTube Music, and ECG app.',
    sku: 'FITB-CH6-BLK',
    brand: 'Fitbit',
    category: 'Sports',
    subcategory: 'Fitness Trackers',
    price: 159.99,
    rating: 4.3,
    reviewCount: 4321,
    inStock: true,
    stockCount: 80,
    imageUrl: 'https://placehold.co/400x400?text=Fitbit+Charge+6',
    attributes: { color: 'Black', battery: '7 days', gps: 'Built-in' },
    tags: ['fitness', 'health', 'google'],
  },
  {
    title: 'Peloton Bike+',
    description: 'Indoor cycling bike with rotating 24" HD touchscreen, auto-follow resistance, and Apple GymKit.',
    sku: 'PELO-BIKEPLUS',
    brand: 'Peloton',
    category: 'Sports',
    subcategory: 'Exercise Equipment',
    price: 2495.00,
    originalPrice: 2895.00,
    rating: 4.4,
    reviewCount: 2345,
    inStock: false,
    stockCount: 0,
    imageUrl: 'https://placehold.co/400x400?text=Peloton+Bike+',
    attributes: { color: 'Black', screen: '24"', resistance: 'Magnetic' },
    tags: ['fitness', 'cycling', 'sale'],
  },
  {
    title: 'Ray-Ban Wayfarer Classic',
    description: 'Iconic acetate frame with polarized lenses. The most recognizable sunglasses in history.',
    sku: 'RAYB-WAY-BLK-POL',
    brand: 'Ray-Ban',
    category: 'Clothing',
    subcategory: 'Accessories',
    price: 183.00,
    rating: 4.6,
    reviewCount: 15678,
    inStock: true,
    stockCount: 100,
    imageUrl: 'https://placehold.co/400x400?text=Ray-Ban+Wayfarer',
    attributes: { color: 'Black', lenses: 'Polarized', material: 'Acetate' },
    tags: ['classic', 'icon', 'sunglasses'],
  },
  {
    title: 'Fossil Gen 6 Smartwatch 44mm',
    description: 'Wear OS smartwatch with Snapdragon Wear 4100+ chip, SpO2 sensor, and Google Pay.',
    sku: 'FOSS-GEN6-44-SLV',
    brand: 'Fossil',
    category: 'Electronics',
    subcategory: 'Smartwatches',
    price: 249.99,
    originalPrice: 295.00,
    rating: 4.2,
    reviewCount: 1234,
    inStock: true,
    stockCount: 35,
    imageUrl: 'https://placehold.co/400x400?text=Fossil+Gen+6',
    attributes: { color: 'Silver', size: '44mm', os: 'Wear OS' },
    tags: ['smartwatch', 'sale'],
  },
  {
    title: 'Lodge Cast Iron Skillet 12"',
    description: 'Pre-seasoned cast iron skillet that gets better with use. Made in USA since 1896.',
    sku: 'LODG-L10SK3-12',
    brand: 'Lodge',
    category: 'Home & Garden',
    subcategory: 'Cookware',
    price: 49.99,
    rating: 4.8,
    reviewCount: 45678,
    inStock: true,
    stockCount: 250,
    imageUrl: 'https://placehold.co/400x400?text=Lodge+Skillet',
    attributes: { size: '12"', material: 'Cast iron', compatible: 'All stovetops + oven' },
    tags: ['made-in-usa', 'bestseller', 'kitchen'],
  },
  // Additional products to reach 60
  {
    title: 'Apple Watch Series 10 45mm',
    description: 'Thinnest Apple Watch ever with larger display, faster charging, and sleep apnea detection.',
    sku: 'APPL-AWS10-45-BLK',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Smartwatches',
    price: 429.99,
    rating: 4.7,
    reviewCount: 5432,
    inStock: true,
    stockCount: 60,
    imageUrl: 'https://placehold.co/400x400?text=Apple+Watch+S10',
    attributes: { color: 'Midnight', size: '45mm', material: 'Aluminum' },
    tags: ['apple', 'new', 'fitness'],
  },
  {
    title: 'Bose QuietComfort 45',
    description: 'Wireless noise cancelling headphones with adjustable EQ, 24-hour battery, and comfort fit.',
    sku: 'BOSE-QC45-WHT',
    brand: 'Bose',
    category: 'Electronics',
    subcategory: 'Headphones',
    price: 279.99,
    originalPrice: 329.99,
    rating: 4.6,
    reviewCount: 6543,
    inStock: true,
    stockCount: 75,
    imageUrl: 'https://placehold.co/400x400?text=Bose+QC45',
    attributes: { color: 'White Smoke', type: 'Over-ear', connectivity: 'Bluetooth' },
    tags: ['noise-canceling', 'sale'],
  },
  {
    title: 'Adidas Ultraboost 23',
    description: 'Responsive running shoe with BOOST midsole, Primeknit+ upper, and Continental rubber outsole.',
    sku: 'ADID-UB23-BLK-10',
    brand: 'Adidas',
    category: 'Footwear',
    subcategory: 'Running Shoes',
    price: 190.00,
    rating: 4.5,
    reviewCount: 8901,
    inStock: true,
    stockCount: 70,
    imageUrl: 'https://placehold.co/400x400?text=Ultraboost+23',
    attributes: { color: 'Core Black', size: '10', material: 'Primeknit' },
    tags: ['running', 'boost', 'adidas'],
  },
  {
    title: 'Weber Spirit II E-310 Gas Grill',
    description: 'Three-burner gas grill with GS4 grilling system, iGrill 3 compatible, and side tables.',
    sku: 'WEBE-SPII-E310',
    brand: 'Weber',
    category: 'Home & Garden',
    subcategory: 'Grills',
    price: 549.99,
    rating: 4.7,
    reviewCount: 3456,
    inStock: true,
    stockCount: 12,
    imageUrl: 'https://placehold.co/400x400?text=Weber+Spirit+II',
    attributes: { color: 'Black', burners: '3', fuel: 'Propane' },
    tags: ['outdoor', 'bbq', 'summer'],
  },
  {
    title: 'Patagonia Better Sweater Fleece',
    description: 'Classic zip-up fleece made from 100% recycled polyester. Fair Trade Certified.',
    sku: 'PATA-BSF-NVY-M',
    brand: 'Patagonia',
    category: 'Clothing',
    subcategory: "Men's Fleece",
    price: 139.00,
    rating: 4.8,
    reviewCount: 7890,
    inStock: true,
    stockCount: 55,
    imageUrl: 'https://placehold.co/400x400?text=Better+Sweater',
    attributes: { color: 'Navy', size: 'M', material: 'Recycled polyester' },
    tags: ['sustainable', 'outdoor', 'classic'],
  },
  {
    title: 'Kindle Paperwhite 16GB',
    description: 'Waterproof e-reader with 6.8" glare-free display, adjustable warm light, and 10-week battery.',
    sku: 'AMAZ-KPW-16GB',
    brand: 'Amazon',
    category: 'Electronics',
    subcategory: 'E-Readers',
    price: 139.99,
    rating: 4.7,
    reviewCount: 34567,
    inStock: true,
    stockCount: 200,
    imageUrl: 'https://placehold.co/400x400?text=Kindle+Paperwhite',
    attributes: { color: 'Black', storage: '16GB', display: '6.8"' },
    tags: ['reading', 'amazon', 'waterproof'],
  },
  {
    title: 'Lululemon Align Pant 25"',
    description: 'Buttery-soft yoga pants with Nulu fabric for a naked feel. 4-way stretch.',
    sku: 'LULU-ALIGN-25-BLK-6',
    brand: 'Lululemon',
    category: 'Clothing',
    subcategory: "Women's Activewear",
    price: 98.00,
    rating: 4.7,
    reviewCount: 23456,
    inStock: true,
    stockCount: 90,
    imageUrl: 'https://placehold.co/400x400?text=Align+Pant',
    attributes: { color: 'Black', size: '6', inseam: '25"' },
    tags: ['yoga', 'activewear', 'bestseller'],
  },
  {
    title: 'Dr. Martens 1460 Boot',
    description: 'The original 8-eye boot with air-cushioned sole, Goodyear welted construction.',
    sku: 'DRMT-1460-BLK-9',
    brand: 'Dr. Martens',
    category: 'Footwear',
    subcategory: 'Boots',
    price: 170.00,
    rating: 4.5,
    reviewCount: 12345,
    inStock: true,
    stockCount: 65,
    imageUrl: 'https://placehold.co/400x400?text=Dr.+Martens+1460',
    attributes: { color: 'Black', size: '9', material: 'Smooth leather' },
    tags: ['classic', 'icon', 'durable'],
  },
  {
    title: 'Vitamix 5200 Blender',
    description: 'Variable speed control lets you fine-tune texture. Aircraft-grade stainless steel blades.',
    sku: 'VITA-5200-BLK',
    brand: 'Vitamix',
    category: 'Home & Garden',
    subcategory: 'Kitchen Appliances',
    price: 449.99,
    rating: 4.8,
    reviewCount: 9012,
    inStock: true,
    stockCount: 30,
    imageUrl: 'https://placehold.co/400x400?text=Vitamix+5200',
    attributes: { color: 'Black', capacity: '64oz', motor: '2.0 HP' },
    tags: ['kitchen', 'premium', 'smoothies'],
  },
  {
    title: 'TRX All-in-One Suspension Trainer',
    description: 'Professional-grade suspension training system. Adjustable for all fitness levels.',
    sku: 'TRX-AIO-HOME',
    brand: 'TRX',
    category: 'Sports',
    subcategory: 'Exercise Equipment',
    price: 169.99,
    originalPrice: 199.99,
    rating: 4.6,
    reviewCount: 5678,
    inStock: true,
    stockCount: 85,
    imageUrl: 'https://placehold.co/400x400?text=TRX+Trainer',
    attributes: { color: 'Black/Yellow', material: 'Nylon', maxWeight: '350 lbs' },
    tags: ['fitness', 'bodyweight', 'sale'],
  },
];

const insert = db.prepare(`
  INSERT INTO products (
    id, title, description, sku, brand, category, subcategory,
    price, originalPrice, rating, reviewCount, inStock, stockCount,
    imageUrl, attributes, tags, createdAt
  ) VALUES (
    @id, @title, @description, @sku, @brand, @category, @subcategory,
    @price, @originalPrice, @rating, @reviewCount, @inStock, @stockCount,
    @imageUrl, @attributes, @tags, @createdAt
  )
`);

const insertMany = db.transaction((items: SeedProduct[]) => {
  for (const item of items) {
    insert.run({
      id: uuidv4(),
      title: item.title,
      description: item.description,
      sku: item.sku,
      brand: item.brand,
      category: item.category,
      subcategory: item.subcategory,
      price: item.price,
      originalPrice: item.originalPrice ?? null,
      rating: item.rating,
      reviewCount: item.reviewCount,
      inStock: item.inStock ? 1 : 0,
      stockCount: item.stockCount,
      imageUrl: item.imageUrl,
      attributes: JSON.stringify(item.attributes),
      tags: JSON.stringify(item.tags),
      createdAt: new Date().toISOString(),
    });
  }
});

insertMany(products);
console.log(`Seeded ${products.length} products into the database`);
